# Generated by Django 4.2.21 on 2025-05-10 18:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_reservation', models.DateField(default=django.utils.timezone.now)),
                ('amount_of_children', models.PositiveIntegerField(default=0)),
                ('amount_of_adults', models.PositiveIntegerField(default=0)),
                ('is_confirmed', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_number_of_participants', models.PositiveIntegerField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('place_id', models.IntegerField()),
                ('tour_type', models.CharField(choices=[('all inclusive', 'All Inclusive'), ('standard', 'Standard'), ('exclusive', 'Exclusive')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('country', models.CharField(max_length=45)),
                ('region', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('accommodation', models.CharField(max_length=45)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=45)),
                ('date_of_birth', models.DateField()),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile/')),
            ],
        ),
        migrations.CreateModel(
            name='TourReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_price_reduced', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_links', to='TravelApp.reservation')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_links', to='TravelApp.tour')),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervised_tours', to='TravelApp.user'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='TravelApp.user'),
        ),
    ]
