# Generated by Django 4.2.21 on 2025-05-10 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TravelApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['is_confirmed']},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['is_active']},
        ),
        migrations.AlterModelOptions(
            name='tourreservation',
            options={'ordering': ['is_active']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name']},
        ),
    ]
